-- ============================================================
-- SQL SCRIPT: إنشاء جداول الموقع الرسمي للنائب مراد لعيداني
-- ============================================================

-- 1. جدول الشكاوى والاقتراحات (Complaints)
CREATE TABLE IF NOT EXISTS public.complaints (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    location TEXT NOT NULL,
    type TEXT NOT NULL,
    subject TEXT NOT NULL,
    details TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    response TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. جدول رسائل التواصل (Contact Messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. جدول الأخبار (News)
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- تفعيل سياسات الأمان (Row Level Security) للسماح بالقراءة والإرسال
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- سياسات الشكاوى
CREATE POLICY "Allow public insert to complaints" ON public.complaints FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow public read complaints" ON public.complaints FOR SELECT TO anon USING (true);
CREATE POLICY "Allow public update complaints" ON public.complaints FOR UPDATE TO anon USING (true);

-- سياسات الرسائل
CREATE POLICY "Allow public insert to messages" ON public.messages FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow public read messages" ON public.messages FOR SELECT TO anon USING (true);
CREATE POLICY "Allow public update messages" ON public.messages FOR UPDATE TO anon USING (true);

-- سياسات الأخبار
CREATE POLICY "Allow public read news" ON public.news FOR SELECT TO anon USING (true);
CREATE POLICY "Allow public insert news" ON public.news FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow public update news" ON public.news FOR UPDATE TO anon USING (true);
CREATE POLICY "Allow public delete news" ON public.news FOR DELETE TO anon USING (true);
